FROM golang:1.26.4-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o gateway-bin ./gateway

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/gateway-bin .
EXPOSE 8080
CMD ["./gateway-bin"]