// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: proto/auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessLevel int32

const (
	AccessLevel_DENIED     AccessLevel = 0
	AccessLevel_FULL       AccessLevel = 1
	AccessLevel_PARTIAL    AccessLevel = 2
	AccessLevel_ANONYMIZED AccessLevel = 3
	AccessLevel_AGGREGATED AccessLevel = 4
)

// Enum value maps for AccessLevel.
var (
	AccessLevel_name = map[int32]string{
		0: "DENIED",
		1: "FULL",
		2: "PARTIAL",
		3: "ANONYMIZED",
		4: "AGGREGATED",
	}
	AccessLevel_value = map[string]int32{
		"DENIED":     0,
		"FULL":       1,
		"PARTIAL":    2,
		"ANONYMIZED": 3,
		"AGGREGATED": 4,
	}
)

func (x AccessLevel) Enum() *AccessLevel {
	p := new(AccessLevel)
	*p = x
	return p
}

func (x AccessLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_auth_proto_enumTypes[0].Descriptor()
}

func (AccessLevel) Type() protoreflect.EnumType {
	return &file_proto_auth_proto_enumTypes[0]
}

func (x AccessLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessLevel.Descriptor instead.
func (AccessLevel) EnumDescriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{0}
}

type Decision int32

const (
	Decision_DENY  Decision = 0
	Decision_ALLOW Decision = 1
)

// Enum value maps for Decision.
var (
	Decision_name = map[int32]string{
		0: "DENY",
		1: "ALLOW",
	}
	Decision_value = map[string]int32{
		"DENY":  0,
		"ALLOW": 1,
	}
)

func (x Decision) Enum() *Decision {
	p := new(Decision)
	*p = x
	return p
}

func (x Decision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Decision) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_auth_proto_enumTypes[1].Descriptor()
}

func (Decision) Type() protoreflect.EnumType {
	return &file_proto_auth_proto_enumTypes[1]
}

func (x Decision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Decision.Descriptor instead.
func (Decision) EnumDescriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{1}
}

type AuthorizeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Username        string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Role            string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	TargetPatientId string                 `protobuf:"bytes,3,opt,name=target_patient_id,json=targetPatientId,proto3" json:"target_patient_id,omitempty"`
	ProjectId       string                 `protobuf:"bytes,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuthorizeRequest) Reset() {
	*x = AuthorizeRequest{}
	mi := &file_proto_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeRequest) ProtoMessage() {}

func (x *AuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizeRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthorizeRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AuthorizeRequest) GetTargetPatientId() string {
	if x != nil {
		return x.TargetPatientId
	}
	return ""
}

func (x *AuthorizeRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type AuthorizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decision      Decision               `protobuf:"varint,1,opt,name=decision,proto3,enum=auth.Decision" json:"decision,omitempty"`
	AccessLevel   AccessLevel            `protobuf:"varint,2,opt,name=access_level,json=accessLevel,proto3,enum=auth.AccessLevel" json:"access_level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeResponse) Reset() {
	*x = AuthorizeResponse{}
	mi := &file_proto_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeResponse) ProtoMessage() {}

func (x *AuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorizeResponse) GetDecision() Decision {
	if x != nil {
		return x.Decision
	}
	return Decision_DENY
}

func (x *AuthorizeResponse) GetAccessLevel() AccessLevel {
	if x != nil {
		return x.AccessLevel
	}
	return AccessLevel_DENIED
}

func (x *AuthorizeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_auth_proto protoreflect.FileDescriptor

const file_proto_auth_proto_rawDesc = "" +
	"\n" +
	"\x10proto/auth.proto\x12\x04auth\"\x8d\x01\n" +
	"\x10AuthorizeRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12*\n" +
	"\x11target_patient_id\x18\x03 \x01(\tR\x0ftargetPatientId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x04 \x01(\tR\tprojectId\"\x8f\x01\n" +
	"\x11AuthorizeResponse\x12*\n" +
	"\bdecision\x18\x01 \x01(\x0e2\x0e.auth.DecisionR\bdecision\x124\n" +
	"\faccess_level\x18\x02 \x01(\x0e2\x11.auth.AccessLevelR\vaccessLevel\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage*P\n" +
	"\vAccessLevel\x12\n" +
	"\n" +
	"\x06DENIED\x10\x00\x12\b\n" +
	"\x04FULL\x10\x01\x12\v\n" +
	"\aPARTIAL\x10\x02\x12\x0e\n" +
	"\n" +
	"ANONYMIZED\x10\x03\x12\x0e\n" +
	"\n" +
	"AGGREGATED\x10\x04*\x1f\n" +
	"\bDecision\x12\b\n" +
	"\x04DENY\x10\x00\x12\t\n" +
	"\x05ALLOW\x10\x012T\n" +
	"\x14AuthorizationService\x12<\n" +
	"\tAuthorize\x12\x16.auth.AuthorizeRequest\x1a\x17.auth.AuthorizeResponseB!Z\x1fgateway-auth-service/proto/authb\x06proto3"

var (
	file_proto_auth_proto_rawDescOnce sync.Once
	file_proto_auth_proto_rawDescData []byte
)

func file_proto_auth_proto_rawDescGZIP() []byte {
	file_proto_auth_proto_rawDescOnce.Do(func() {
		file_proto_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_auth_proto_rawDesc), len(file_proto_auth_proto_rawDesc)))
	})
	return file_proto_auth_proto_rawDescData
}

var file_proto_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_auth_proto_goTypes = []any{
	(AccessLevel)(0),          // 0: auth.AccessLevel
	(Decision)(0),             // 1: auth.Decision
	(*AuthorizeRequest)(nil),  // 2: auth.AuthorizeRequest
	(*AuthorizeResponse)(nil), // 3: auth.AuthorizeResponse
}
var file_proto_auth_proto_depIdxs = []int32{
	1, // 0: auth.AuthorizeResponse.decision:type_name -> auth.Decision
	0, // 1: auth.AuthorizeResponse.access_level:type_name -> auth.AccessLevel
	2, // 2: auth.AuthorizationService.Authorize:input_type -> auth.AuthorizeRequest
	3, // 3: auth.AuthorizationService.Authorize:output_type -> auth.AuthorizeResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_auth_proto_init() }
func file_proto_auth_proto_init() {
	if File_proto_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auth_proto_rawDesc), len(file_proto_auth_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_auth_proto_goTypes,
		DependencyIndexes: file_proto_auth_proto_depIdxs,
		EnumInfos:         file_proto_auth_proto_enumTypes,
		MessageInfos:      file_proto_auth_proto_msgTypes,
	}.Build()
	File_proto_auth_proto = out.File
	file_proto_auth_proto_goTypes = nil
	file_proto_auth_proto_depIdxs = nil
}
