// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: datatransform/v1/datatransform.proto

package datatransformv1

import (
	v1 "gateway-auth-service/proto/patientdata/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Nível de acesso determinado pelo Authorization Service (repassado pela Gateway).
type AccessLevel int32

const (
	AccessLevel_ACCESS_LEVEL_UNSPECIFIED AccessLevel = 0
	AccessLevel_FULL                     AccessLevel = 1 // dados completos
	AccessLevel_PARTIAL                  AccessLevel = 2 // iniciais, sem CPF/CNS, ano de nascimento
	AccessLevel_ANONYMIZED               AccessLevel = 3 // pseudônimo, sem identificadores diretos, faixa etária
	AccessLevel_AGGREGATED               AccessLevel = 4 // apenas totais/percentuais
)

// Enum value maps for AccessLevel.
var (
	AccessLevel_name = map[int32]string{
		0: "ACCESS_LEVEL_UNSPECIFIED",
		1: "FULL",
		2: "PARTIAL",
		3: "ANONYMIZED",
		4: "AGGREGATED",
	}
	AccessLevel_value = map[string]int32{
		"ACCESS_LEVEL_UNSPECIFIED": 0,
		"FULL":                     1,
		"PARTIAL":                  2,
		"ANONYMIZED":               3,
		"AGGREGATED":               4,
	}
)

func (x AccessLevel) Enum() *AccessLevel {
	p := new(AccessLevel)
	*p = x
	return p
}

func (x AccessLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_datatransform_v1_datatransform_proto_enumTypes[0].Descriptor()
}

func (AccessLevel) Type() protoreflect.EnumType {
	return &file_datatransform_v1_datatransform_proto_enumTypes[0]
}

func (x AccessLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessLevel.Descriptor instead.
func (AccessLevel) EnumDescriptor() ([]byte, []int) {
	return file_datatransform_v1_datatransform_proto_rawDescGZIP(), []int{0}
}

type TransformPatientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patient       *v1.Patient            `protobuf:"bytes,1,opt,name=patient,proto3" json:"patient,omitempty"`
	AccessLevel   AccessLevel            `protobuf:"varint,2,opt,name=access_level,json=accessLevel,proto3,enum=datatransform.v1.AccessLevel" json:"access_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformPatientRequest) Reset() {
	*x = TransformPatientRequest{}
	mi := &file_datatransform_v1_datatransform_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformPatientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformPatientRequest) ProtoMessage() {}

func (x *TransformPatientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datatransform_v1_datatransform_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformPatientRequest.ProtoReflect.Descriptor instead.
func (*TransformPatientRequest) Descriptor() ([]byte, []int) {
	return file_datatransform_v1_datatransform_proto_rawDescGZIP(), []int{0}
}

func (x *TransformPatientRequest) GetPatient() *v1.Patient {
	if x != nil {
		return x.Patient
	}
	return nil
}

func (x *TransformPatientRequest) GetAccessLevel() AccessLevel {
	if x != nil {
		return x.AccessLevel
	}
	return AccessLevel_ACCESS_LEVEL_UNSPECIFIED
}

type TransformClinicalSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       *v1.ClinicalSummary    `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	AccessLevel   AccessLevel            `protobuf:"varint,2,opt,name=access_level,json=accessLevel,proto3,enum=datatransform.v1.AccessLevel" json:"access_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformClinicalSummaryRequest) Reset() {
	*x = TransformClinicalSummaryRequest{}
	mi := &file_datatransform_v1_datatransform_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformClinicalSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformClinicalSummaryRequest) ProtoMessage() {}

func (x *TransformClinicalSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datatransform_v1_datatransform_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformClinicalSummaryRequest.ProtoReflect.Descriptor instead.
func (*TransformClinicalSummaryRequest) Descriptor() ([]byte, []int) {
	return file_datatransform_v1_datatransform_proto_rawDescGZIP(), []int{1}
}

func (x *TransformClinicalSummaryRequest) GetSummary() *v1.ClinicalSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *TransformClinicalSummaryRequest) GetAccessLevel() AccessLevel {
	if x != nil {
		return x.AccessLevel
	}
	return AccessLevel_ACCESS_LEVEL_UNSPECIFIED
}

type TransformClinicalHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patient       *v1.Patient            `protobuf:"bytes,1,opt,name=patient,proto3" json:"patient,omitempty"`
	Events        []*v1.ClinicalEvent    `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	AccessLevel   AccessLevel            `protobuf:"varint,3,opt,name=access_level,json=accessLevel,proto3,enum=datatransform.v1.AccessLevel" json:"access_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformClinicalHistoryRequest) Reset() {
	*x = TransformClinicalHistoryRequest{}
	mi := &file_datatransform_v1_datatransform_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformClinicalHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformClinicalHistoryRequest) ProtoMessage() {}

func (x *TransformClinicalHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datatransform_v1_datatransform_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformClinicalHistoryRequest.ProtoReflect.Descriptor instead.
func (*TransformClinicalHistoryRequest) Descriptor() ([]byte, []int) {
	return file_datatransform_v1_datatransform_proto_rawDescGZIP(), []int{2}
}

func (x *TransformClinicalHistoryRequest) GetPatient() *v1.Patient {
	if x != nil {
		return x.Patient
	}
	return nil
}

func (x *TransformClinicalHistoryRequest) GetEvents() []*v1.ClinicalEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *TransformClinicalHistoryRequest) GetAccessLevel() AccessLevel {
	if x != nil {
		return x.AccessLevel
	}
	return AccessLevel_ACCESS_LEVEL_UNSPECIFIED
}

type TransformPatientListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patients      []*v1.Patient          `protobuf:"bytes,1,rep,name=patients,proto3" json:"patients,omitempty"`
	AccessLevel   AccessLevel            `protobuf:"varint,2,opt,name=access_level,json=accessLevel,proto3,enum=datatransform.v1.AccessLevel" json:"access_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformPatientListRequest) Reset() {
	*x = TransformPatientListRequest{}
	mi := &file_datatransform_v1_datatransform_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformPatientListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformPatientListRequest) ProtoMessage() {}

func (x *TransformPatientListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datatransform_v1_datatransform_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformPatientListRequest.ProtoReflect.Descriptor instead.
func (*TransformPatientListRequest) Descriptor() ([]byte, []int) {
	return file_datatransform_v1_datatransform_proto_rawDescGZIP(), []int{3}
}

func (x *TransformPatientListRequest) GetPatients() []*v1.Patient {
	if x != nil {
		return x.Patients
	}
	return nil
}

func (x *TransformPatientListRequest) GetAccessLevel() AccessLevel {
	if x != nil {
		return x.AccessLevel
	}
	return AccessLevel_ACCESS_LEVEL_UNSPECIFIED
}

// Um paciente da coorte com seus exames (usado em TransformCohortExams).
type PatientExams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patient       *v1.Patient            `protobuf:"bytes,1,opt,name=patient,proto3" json:"patient,omitempty"`
	Exams         []*v1.ClinicalEvent    `protobuf:"bytes,2,rep,name=exams,proto3" json:"exams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatientExams) Reset() {
	*x = PatientExams{}
	mi := &file_datatransform_v1_datatransform_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatientExams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatientExams) ProtoMessage() {}

func (x *PatientExams) ProtoReflect() protoreflect.Message {
	mi := &file_datatransform_v1_datatransform_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatientExams.ProtoReflect.Descriptor instead.
func (*PatientExams) Descriptor() ([]byte, []int) {
	return file_datatransform_v1_datatransform_proto_rawDescGZIP(), []int{4}
}

func (x *PatientExams) GetPatient() *v1.Patient {
	if x != nil {
		return x.Patient
	}
	return nil
}

func (x *PatientExams) GetExams() []*v1.ClinicalEvent {
	if x != nil {
		return x.Exams
	}
	return nil
}

type TransformCohortExamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patients      []*PatientExams        `protobuf:"bytes,1,rep,name=patients,proto3" json:"patients,omitempty"`
	AccessLevel   AccessLevel            `protobuf:"varint,2,opt,name=access_level,json=accessLevel,proto3,enum=datatransform.v1.AccessLevel" json:"access_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformCohortExamsRequest) Reset() {
	*x = TransformCohortExamsRequest{}
	mi := &file_datatransform_v1_datatransform_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformCohortExamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformCohortExamsRequest) ProtoMessage() {}

func (x *TransformCohortExamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datatransform_v1_datatransform_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformCohortExamsRequest.ProtoReflect.Descriptor instead.
func (*TransformCohortExamsRequest) Descriptor() ([]byte, []int) {
	return file_datatransform_v1_datatransform_proto_rawDescGZIP(), []int{5}
}

func (x *TransformCohortExamsRequest) GetPatients() []*PatientExams {
	if x != nil {
		return x.Patients
	}
	return nil
}

func (x *TransformCohortExamsRequest) GetAccessLevel() AccessLevel {
	if x != nil {
		return x.AccessLevel
	}
	return AccessLevel_ACCESS_LEVEL_UNSPECIFIED
}

type TransformCohortStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *v1.CohortStatistics   `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformCohortStatisticsRequest) Reset() {
	*x = TransformCohortStatisticsRequest{}
	mi := &file_datatransform_v1_datatransform_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformCohortStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformCohortStatisticsRequest) ProtoMessage() {}

func (x *TransformCohortStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datatransform_v1_datatransform_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformCohortStatisticsRequest.ProtoReflect.Descriptor instead.
func (*TransformCohortStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_datatransform_v1_datatransform_proto_rawDescGZIP(), []int{6}
}

func (x *TransformCohortStatisticsRequest) GetStats() *v1.CohortStatistics {
	if x != nil {
		return x.Stats
	}
	return nil
}

type TransformProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*v1.Project          `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformProjectsRequest) Reset() {
	*x = TransformProjectsRequest{}
	mi := &file_datatransform_v1_datatransform_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformProjectsRequest) ProtoMessage() {}

func (x *TransformProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datatransform_v1_datatransform_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformProjectsRequest.ProtoReflect.Descriptor instead.
func (*TransformProjectsRequest) Descriptor() ([]byte, []int) {
	return file_datatransform_v1_datatransform_proto_rawDescGZIP(), []int{7}
}

func (x *TransformProjectsRequest) GetProjects() []*v1.Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

// Par chave→contagem→percentual usado nas distribuições agregadas.
type Percentage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Percentage    float64                `protobuf:"fixed64,3,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Percentage) Reset() {
	*x = Percentage{}
	mi := &file_datatransform_v1_datatransform_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Percentage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Percentage) ProtoMessage() {}

func (x *Percentage) ProtoReflect() protoreflect.Message {
	mi := &file_datatransform_v1_datatransform_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Percentage.ProtoReflect.Descriptor instead.
func (*Percentage) Descriptor() ([]byte, []int) {
	return file_datatransform_v1_datatransform_proto_rawDescGZIP(), []int{8}
}

func (x *Percentage) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Percentage) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Percentage) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

type CohortStatisticsResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ConditionCode       string                 `protobuf:"bytes,1,opt,name=condition_code,json=conditionCode,proto3" json:"condition_code,omitempty"`
	TotalPatients       int64                  `protobuf:"varint,2,opt,name=total_patients,json=totalPatients,proto3" json:"total_patients,omitempty"`
	BySex               []*Percentage          `protobuf:"bytes,3,rep,name=by_sex,json=bySex,proto3" json:"by_sex,omitempty"`
	ByAgeRange          []*Percentage          `protobuf:"bytes,4,rep,name=by_age_range,json=byAgeRange,proto3" json:"by_age_range,omitempty"`
	MeanHba1C           float64                `protobuf:"fixed64,5,opt,name=mean_hba1c,json=meanHba1c,proto3" json:"mean_hba1c,omitempty"`
	MedianHba1C         float64                `protobuf:"fixed64,6,opt,name=median_hba1c,json=medianHba1c,proto3" json:"median_hba1c,omitempty"`
	MedicationFrequency []*Percentage          `protobuf:"bytes,7,rep,name=medication_frequency,json=medicationFrequency,proto3" json:"medication_frequency,omitempty"`
	ByDepartment        []*Percentage          `protobuf:"bytes,8,rep,name=by_department,json=byDepartment,proto3" json:"by_department,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CohortStatisticsResponse) Reset() {
	*x = CohortStatisticsResponse{}
	mi := &file_datatransform_v1_datatransform_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CohortStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CohortStatisticsResponse) ProtoMessage() {}

func (x *CohortStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datatransform_v1_datatransform_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CohortStatisticsResponse.ProtoReflect.Descriptor instead.
func (*CohortStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_datatransform_v1_datatransform_proto_rawDescGZIP(), []int{9}
}

func (x *CohortStatisticsResponse) GetConditionCode() string {
	if x != nil {
		return x.ConditionCode
	}
	return ""
}

func (x *CohortStatisticsResponse) GetTotalPatients() int64 {
	if x != nil {
		return x.TotalPatients
	}
	return 0
}

func (x *CohortStatisticsResponse) GetBySex() []*Percentage {
	if x != nil {
		return x.BySex
	}
	return nil
}

func (x *CohortStatisticsResponse) GetByAgeRange() []*Percentage {
	if x != nil {
		return x.ByAgeRange
	}
	return nil
}

func (x *CohortStatisticsResponse) GetMeanHba1C() float64 {
	if x != nil {
		return x.MeanHba1C
	}
	return 0
}

func (x *CohortStatisticsResponse) GetMedianHba1C() float64 {
	if x != nil {
		return x.MedianHba1C
	}
	return 0
}

func (x *CohortStatisticsResponse) GetMedicationFrequency() []*Percentage {
	if x != nil {
		return x.MedicationFrequency
	}
	return nil
}

func (x *CohortStatisticsResponse) GetByDepartment() []*Percentage {
	if x != nil {
		return x.ByDepartment
	}
	return nil
}

var File_datatransform_v1_datatransform_proto protoreflect.FileDescriptor

const file_datatransform_v1_datatransform_proto_rawDesc = "" +
	"\n" +
	"$datatransform/v1/datatransform.proto\x12\x10datatransform.v1\x1a patientdata/v1/patientdata.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x8e\x01\n" +
	"\x17TransformPatientRequest\x121\n" +
	"\apatient\x18\x01 \x01(\v2\x17.patientdata.v1.PatientR\apatient\x12@\n" +
	"\faccess_level\x18\x02 \x01(\x0e2\x1d.datatransform.v1.AccessLevelR\vaccessLevel\"\x9e\x01\n" +
	"\x1fTransformClinicalSummaryRequest\x129\n" +
	"\asummary\x18\x01 \x01(\v2\x1f.patientdata.v1.ClinicalSummaryR\asummary\x12@\n" +
	"\faccess_level\x18\x02 \x01(\x0e2\x1d.datatransform.v1.AccessLevelR\vaccessLevel\"\xcd\x01\n" +
	"\x1fTransformClinicalHistoryRequest\x121\n" +
	"\apatient\x18\x01 \x01(\v2\x17.patientdata.v1.PatientR\apatient\x125\n" +
	"\x06events\x18\x02 \x03(\v2\x1d.patientdata.v1.ClinicalEventR\x06events\x12@\n" +
	"\faccess_level\x18\x03 \x01(\x0e2\x1d.datatransform.v1.AccessLevelR\vaccessLevel\"\x94\x01\n" +
	"\x1bTransformPatientListRequest\x123\n" +
	"\bpatients\x18\x01 \x03(\v2\x17.patientdata.v1.PatientR\bpatients\x12@\n" +
	"\faccess_level\x18\x02 \x01(\x0e2\x1d.datatransform.v1.AccessLevelR\vaccessLevel\"v\n" +
	"\fPatientExams\x121\n" +
	"\apatient\x18\x01 \x01(\v2\x17.patientdata.v1.PatientR\apatient\x123\n" +
	"\x05exams\x18\x02 \x03(\v2\x1d.patientdata.v1.ClinicalEventR\x05exams\"\x9b\x01\n" +
	"\x1bTransformCohortExamsRequest\x12:\n" +
	"\bpatients\x18\x01 \x03(\v2\x1e.datatransform.v1.PatientExamsR\bpatients\x12@\n" +
	"\faccess_level\x18\x02 \x01(\x0e2\x1d.datatransform.v1.AccessLevelR\vaccessLevel\"Z\n" +
	" TransformCohortStatisticsRequest\x126\n" +
	"\x05stats\x18\x01 \x01(\v2 .patientdata.v1.CohortStatisticsR\x05stats\"O\n" +
	"\x18TransformProjectsRequest\x123\n" +
	"\bprojects\x18\x01 \x03(\v2\x17.patientdata.v1.ProjectR\bprojects\"T\n" +
	"\n" +
	"Percentage\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12\x1e\n" +
	"\n" +
	"percentage\x18\x03 \x01(\x01R\n" +
	"percentage\"\xb3\x03\n" +
	"\x18CohortStatisticsResponse\x12%\n" +
	"\x0econdition_code\x18\x01 \x01(\tR\rconditionCode\x12%\n" +
	"\x0etotal_patients\x18\x02 \x01(\x03R\rtotalPatients\x123\n" +
	"\x06by_sex\x18\x03 \x03(\v2\x1c.datatransform.v1.PercentageR\x05bySex\x12>\n" +
	"\fby_age_range\x18\x04 \x03(\v2\x1c.datatransform.v1.PercentageR\n" +
	"byAgeRange\x12\x1d\n" +
	"\n" +
	"mean_hba1c\x18\x05 \x01(\x01R\tmeanHba1c\x12!\n" +
	"\fmedian_hba1c\x18\x06 \x01(\x01R\vmedianHba1c\x12O\n" +
	"\x14medication_frequency\x18\a \x03(\v2\x1c.datatransform.v1.PercentageR\x13medicationFrequency\x12A\n" +
	"\rby_department\x18\b \x03(\v2\x1c.datatransform.v1.PercentageR\fbyDepartment*b\n" +
	"\vAccessLevel\x12\x1c\n" +
	"\x18ACCESS_LEVEL_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04FULL\x10\x01\x12\v\n" +
	"\aPARTIAL\x10\x02\x12\x0e\n" +
	"\n" +
	"ANONYMIZED\x10\x03\x12\x0e\n" +
	"\n" +
	"AGGREGATED\x10\x042\xd5\x05\n" +
	"\x14DataTransformService\x12V\n" +
	"\x10TransformPatient\x12).datatransform.v1.TransformPatientRequest\x1a\x17.google.protobuf.Struct\x12f\n" +
	"\x18TransformClinicalSummary\x121.datatransform.v1.TransformClinicalSummaryRequest\x1a\x17.google.protobuf.Struct\x12f\n" +
	"\x18TransformClinicalHistory\x121.datatransform.v1.TransformClinicalHistoryRequest\x1a\x17.google.protobuf.Struct\x12^\n" +
	"\x14TransformPatientList\x12-.datatransform.v1.TransformPatientListRequest\x1a\x17.google.protobuf.Struct\x12^\n" +
	"\x14TransformCohortExams\x12-.datatransform.v1.TransformCohortExamsRequest\x1a\x17.google.protobuf.Struct\x12{\n" +
	"\x19TransformCohortStatistics\x122.datatransform.v1.TransformCohortStatisticsRequest\x1a*.datatransform.v1.CohortStatisticsResponse\x12X\n" +
	"\x11TransformProjects\x12*.datatransform.v1.TransformProjectsRequest\x1a\x17.google.protobuf.StructBFZDgateway-authorization-service/proto/datatransform/v1;datatransformv1b\x06proto3"

var (
	file_datatransform_v1_datatransform_proto_rawDescOnce sync.Once
	file_datatransform_v1_datatransform_proto_rawDescData []byte
)

func file_datatransform_v1_datatransform_proto_rawDescGZIP() []byte {
	file_datatransform_v1_datatransform_proto_rawDescOnce.Do(func() {
		file_datatransform_v1_datatransform_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_datatransform_v1_datatransform_proto_rawDesc), len(file_datatransform_v1_datatransform_proto_rawDesc)))
	})
	return file_datatransform_v1_datatransform_proto_rawDescData
}

var file_datatransform_v1_datatransform_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_datatransform_v1_datatransform_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_datatransform_v1_datatransform_proto_goTypes = []any{
	(AccessLevel)(0),                         // 0: datatransform.v1.AccessLevel
	(*TransformPatientRequest)(nil),          // 1: datatransform.v1.TransformPatientRequest
	(*TransformClinicalSummaryRequest)(nil),  // 2: datatransform.v1.TransformClinicalSummaryRequest
	(*TransformClinicalHistoryRequest)(nil),  // 3: datatransform.v1.TransformClinicalHistoryRequest
	(*TransformPatientListRequest)(nil),      // 4: datatransform.v1.TransformPatientListRequest
	(*PatientExams)(nil),                     // 5: datatransform.v1.PatientExams
	(*TransformCohortExamsRequest)(nil),      // 6: datatransform.v1.TransformCohortExamsRequest
	(*TransformCohortStatisticsRequest)(nil), // 7: datatransform.v1.TransformCohortStatisticsRequest
	(*TransformProjectsRequest)(nil),         // 8: datatransform.v1.TransformProjectsRequest
	(*Percentage)(nil),                       // 9: datatransform.v1.Percentage
	(*CohortStatisticsResponse)(nil),         // 10: datatransform.v1.CohortStatisticsResponse
	(*v1.Patient)(nil),                       // 11: patientdata.v1.Patient
	(*v1.ClinicalSummary)(nil),               // 12: patientdata.v1.ClinicalSummary
	(*v1.ClinicalEvent)(nil),                 // 13: patientdata.v1.ClinicalEvent
	(*v1.CohortStatistics)(nil),              // 14: patientdata.v1.CohortStatistics
	(*v1.Project)(nil),                       // 15: patientdata.v1.Project
	(*structpb.Struct)(nil),                  // 16: google.protobuf.Struct
}
var file_datatransform_v1_datatransform_proto_depIdxs = []int32{
	11, // 0: datatransform.v1.TransformPatientRequest.patient:type_name -> patientdata.v1.Patient
	0,  // 1: datatransform.v1.TransformPatientRequest.access_level:type_name -> datatransform.v1.AccessLevel
	12, // 2: datatransform.v1.TransformClinicalSummaryRequest.summary:type_name -> patientdata.v1.ClinicalSummary
	0,  // 3: datatransform.v1.TransformClinicalSummaryRequest.access_level:type_name -> datatransform.v1.AccessLevel
	11, // 4: datatransform.v1.TransformClinicalHistoryRequest.patient:type_name -> patientdata.v1.Patient
	13, // 5: datatransform.v1.TransformClinicalHistoryRequest.events:type_name -> patientdata.v1.ClinicalEvent
	0,  // 6: datatransform.v1.TransformClinicalHistoryRequest.access_level:type_name -> datatransform.v1.AccessLevel
	11, // 7: datatransform.v1.TransformPatientListRequest.patients:type_name -> patientdata.v1.Patient
	0,  // 8: datatransform.v1.TransformPatientListRequest.access_level:type_name -> datatransform.v1.AccessLevel
	11, // 9: datatransform.v1.PatientExams.patient:type_name -> patientdata.v1.Patient
	13, // 10: datatransform.v1.PatientExams.exams:type_name -> patientdata.v1.ClinicalEvent
	5,  // 11: datatransform.v1.TransformCohortExamsRequest.patients:type_name -> datatransform.v1.PatientExams
	0,  // 12: datatransform.v1.TransformCohortExamsRequest.access_level:type_name -> datatransform.v1.AccessLevel
	14, // 13: datatransform.v1.TransformCohortStatisticsRequest.stats:type_name -> patientdata.v1.CohortStatistics
	15, // 14: datatransform.v1.TransformProjectsRequest.projects:type_name -> patientdata.v1.Project
	9,  // 15: datatransform.v1.CohortStatisticsResponse.by_sex:type_name -> datatransform.v1.Percentage
	9,  // 16: datatransform.v1.CohortStatisticsResponse.by_age_range:type_name -> datatransform.v1.Percentage
	9,  // 17: datatransform.v1.CohortStatisticsResponse.medication_frequency:type_name -> datatransform.v1.Percentage
	9,  // 18: datatransform.v1.CohortStatisticsResponse.by_department:type_name -> datatransform.v1.Percentage
	1,  // 19: datatransform.v1.DataTransformService.TransformPatient:input_type -> datatransform.v1.TransformPatientRequest
	2,  // 20: datatransform.v1.DataTransformService.TransformClinicalSummary:input_type -> datatransform.v1.TransformClinicalSummaryRequest
	3,  // 21: datatransform.v1.DataTransformService.TransformClinicalHistory:input_type -> datatransform.v1.TransformClinicalHistoryRequest
	4,  // 22: datatransform.v1.DataTransformService.TransformPatientList:input_type -> datatransform.v1.TransformPatientListRequest
	6,  // 23: datatransform.v1.DataTransformService.TransformCohortExams:input_type -> datatransform.v1.TransformCohortExamsRequest
	7,  // 24: datatransform.v1.DataTransformService.TransformCohortStatistics:input_type -> datatransform.v1.TransformCohortStatisticsRequest
	8,  // 25: datatransform.v1.DataTransformService.TransformProjects:input_type -> datatransform.v1.TransformProjectsRequest
	16, // 26: datatransform.v1.DataTransformService.TransformPatient:output_type -> google.protobuf.Struct
	16, // 27: datatransform.v1.DataTransformService.TransformClinicalSummary:output_type -> google.protobuf.Struct
	16, // 28: datatransform.v1.DataTransformService.TransformClinicalHistory:output_type -> google.protobuf.Struct
	16, // 29: datatransform.v1.DataTransformService.TransformPatientList:output_type -> google.protobuf.Struct
	16, // 30: datatransform.v1.DataTransformService.TransformCohortExams:output_type -> google.protobuf.Struct
	10, // 31: datatransform.v1.DataTransformService.TransformCohortStatistics:output_type -> datatransform.v1.CohortStatisticsResponse
	16, // 32: datatransform.v1.DataTransformService.TransformProjects:output_type -> google.protobuf.Struct
	26, // [26:33] is the sub-list for method output_type
	19, // [19:26] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_datatransform_v1_datatransform_proto_init() }
func file_datatransform_v1_datatransform_proto_init() {
	if File_datatransform_v1_datatransform_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datatransform_v1_datatransform_proto_rawDesc), len(file_datatransform_v1_datatransform_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_datatransform_v1_datatransform_proto_goTypes,
		DependencyIndexes: file_datatransform_v1_datatransform_proto_depIdxs,
		EnumInfos:         file_datatransform_v1_datatransform_proto_enumTypes,
		MessageInfos:      file_datatransform_v1_datatransform_proto_msgTypes,
	}.Build()
	File_datatransform_v1_datatransform_proto = out.File
	file_datatransform_v1_datatransform_proto_goTypes = nil
	file_datatransform_v1_datatransform_proto_depIdxs = nil
}
