// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.6
// source: datatransform/v1/datatransform.proto

package datatransformv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	structpb "google.golang.org/protobuf/types/known/structpb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataTransformService_TransformPatient_FullMethodName          = "/datatransform.v1.DataTransformService/TransformPatient"
	DataTransformService_TransformClinicalSummary_FullMethodName  = "/datatransform.v1.DataTransformService/TransformClinicalSummary"
	DataTransformService_TransformClinicalHistory_FullMethodName  = "/datatransform.v1.DataTransformService/TransformClinicalHistory"
	DataTransformService_TransformPatientList_FullMethodName      = "/datatransform.v1.DataTransformService/TransformPatientList"
	DataTransformService_TransformCohortExams_FullMethodName      = "/datatransform.v1.DataTransformService/TransformCohortExams"
	DataTransformService_TransformCohortStatistics_FullMethodName = "/datatransform.v1.DataTransformService/TransformCohortStatistics"
	DataTransformService_TransformProjects_FullMethodName         = "/datatransform.v1.DataTransformService/TransformProjects"
)

// DataTransformServiceClient is the client API for DataTransformService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DataTransformService recebe os dados crus + nível de acesso, aplica
// anonimização/agregação e converte para HL7/FHIR. As respostas FHIR são objetos
// JSON (google.protobuf.Struct): um recurso (ex.: Patient) ou um Bundle.
type DataTransformServiceClient interface {
	// Paciente único -> recurso FHIR Patient (com o nível aplicado).
	TransformPatient(ctx context.Context, in *TransformPatientRequest, opts ...grpc.CallOption) (*structpb.Struct, error)
	// Resumo clínico -> Bundle (Patient + Encounter + Condition + Observation + MedicationRequest).
	TransformClinicalSummary(ctx context.Context, in *TransformClinicalSummaryRequest, opts ...grpc.CallOption) (*structpb.Struct, error)
	// Histórico clínico -> Bundle de eventos em ordem temporal.
	TransformClinicalHistory(ctx context.Context, in *TransformClinicalHistoryRequest, opts ...grpc.CallOption) (*structpb.Struct, error)
	// Lista de pacientes (de um médico/estagiário) -> Bundle de Patient.
	TransformPatientList(ctx context.Context, in *TransformPatientListRequest, opts ...grpc.CallOption) (*structpb.Struct, error)
	// Exames de uma coorte, anonimizados -> Bundle (para pesquisadores).
	TransformCohortExams(ctx context.Context, in *TransformCohortExamsRequest, opts ...grpc.CallOption) (*structpb.Struct, error)
	// Estatísticas cruas de uma coorte -> resposta com percentuais (AGGREGATED).
	TransformCohortStatistics(ctx context.Context, in *TransformCohortStatisticsRequest, opts ...grpc.CallOption) (*CohortStatisticsResponse, error)
	// Projetos de pesquisa -> Bundle de ResearchStudy.
	TransformProjects(ctx context.Context, in *TransformProjectsRequest, opts ...grpc.CallOption) (*structpb.Struct, error)
}

type dataTransformServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataTransformServiceClient(cc grpc.ClientConnInterface) DataTransformServiceClient {
	return &dataTransformServiceClient{cc}
}

func (c *dataTransformServiceClient) TransformPatient(ctx context.Context, in *TransformPatientRequest, opts ...grpc.CallOption) (*structpb.Struct, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(structpb.Struct)
	err := c.cc.Invoke(ctx, DataTransformService_TransformPatient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataTransformServiceClient) TransformClinicalSummary(ctx context.Context, in *TransformClinicalSummaryRequest, opts ...grpc.CallOption) (*structpb.Struct, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(structpb.Struct)
	err := c.cc.Invoke(ctx, DataTransformService_TransformClinicalSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataTransformServiceClient) TransformClinicalHistory(ctx context.Context, in *TransformClinicalHistoryRequest, opts ...grpc.CallOption) (*structpb.Struct, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(structpb.Struct)
	err := c.cc.Invoke(ctx, DataTransformService_TransformClinicalHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataTransformServiceClient) TransformPatientList(ctx context.Context, in *TransformPatientListRequest, opts ...grpc.CallOption) (*structpb.Struct, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(structpb.Struct)
	err := c.cc.Invoke(ctx, DataTransformService_TransformPatientList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataTransformServiceClient) TransformCohortExams(ctx context.Context, in *TransformCohortExamsRequest, opts ...grpc.CallOption) (*structpb.Struct, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(structpb.Struct)
	err := c.cc.Invoke(ctx, DataTransformService_TransformCohortExams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataTransformServiceClient) TransformCohortStatistics(ctx context.Context, in *TransformCohortStatisticsRequest, opts ...grpc.CallOption) (*CohortStatisticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CohortStatisticsResponse)
	err := c.cc.Invoke(ctx, DataTransformService_TransformCohortStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataTransformServiceClient) TransformProjects(ctx context.Context, in *TransformProjectsRequest, opts ...grpc.CallOption) (*structpb.Struct, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(structpb.Struct)
	err := c.cc.Invoke(ctx, DataTransformService_TransformProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataTransformServiceServer is the server API for DataTransformService service.
// All implementations must embed UnimplementedDataTransformServiceServer
// for forward compatibility.
//
// DataTransformService recebe os dados crus + nível de acesso, aplica
// anonimização/agregação e converte para HL7/FHIR. As respostas FHIR são objetos
// JSON (google.protobuf.Struct): um recurso (ex.: Patient) ou um Bundle.
type DataTransformServiceServer interface {
	// Paciente único -> recurso FHIR Patient (com o nível aplicado).
	TransformPatient(context.Context, *TransformPatientRequest) (*structpb.Struct, error)
	// Resumo clínico -> Bundle (Patient + Encounter + Condition + Observation + MedicationRequest).
	TransformClinicalSummary(context.Context, *TransformClinicalSummaryRequest) (*structpb.Struct, error)
	// Histórico clínico -> Bundle de eventos em ordem temporal.
	TransformClinicalHistory(context.Context, *TransformClinicalHistoryRequest) (*structpb.Struct, error)
	// Lista de pacientes (de um médico/estagiário) -> Bundle de Patient.
	TransformPatientList(context.Context, *TransformPatientListRequest) (*structpb.Struct, error)
	// Exames de uma coorte, anonimizados -> Bundle (para pesquisadores).
	TransformCohortExams(context.Context, *TransformCohortExamsRequest) (*structpb.Struct, error)
	// Estatísticas cruas de uma coorte -> resposta com percentuais (AGGREGATED).
	TransformCohortStatistics(context.Context, *TransformCohortStatisticsRequest) (*CohortStatisticsResponse, error)
	// Projetos de pesquisa -> Bundle de ResearchStudy.
	TransformProjects(context.Context, *TransformProjectsRequest) (*structpb.Struct, error)
	mustEmbedUnimplementedDataTransformServiceServer()
}

// UnimplementedDataTransformServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataTransformServiceServer struct{}

func (UnimplementedDataTransformServiceServer) TransformPatient(context.Context, *TransformPatientRequest) (*structpb.Struct, error) {
	return nil, status.Error(codes.Unimplemented, "method TransformPatient not implemented")
}
func (UnimplementedDataTransformServiceServer) TransformClinicalSummary(context.Context, *TransformClinicalSummaryRequest) (*structpb.Struct, error) {
	return nil, status.Error(codes.Unimplemented, "method TransformClinicalSummary not implemented")
}
func (UnimplementedDataTransformServiceServer) TransformClinicalHistory(context.Context, *TransformClinicalHistoryRequest) (*structpb.Struct, error) {
	return nil, status.Error(codes.Unimplemented, "method TransformClinicalHistory not implemented")
}
func (UnimplementedDataTransformServiceServer) TransformPatientList(context.Context, *TransformPatientListRequest) (*structpb.Struct, error) {
	return nil, status.Error(codes.Unimplemented, "method TransformPatientList not implemented")
}
func (UnimplementedDataTransformServiceServer) TransformCohortExams(context.Context, *TransformCohortExamsRequest) (*structpb.Struct, error) {
	return nil, status.Error(codes.Unimplemented, "method TransformCohortExams not implemented")
}
func (UnimplementedDataTransformServiceServer) TransformCohortStatistics(context.Context, *TransformCohortStatisticsRequest) (*CohortStatisticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransformCohortStatistics not implemented")
}
func (UnimplementedDataTransformServiceServer) TransformProjects(context.Context, *TransformProjectsRequest) (*structpb.Struct, error) {
	return nil, status.Error(codes.Unimplemented, "method TransformProjects not implemented")
}
func (UnimplementedDataTransformServiceServer) mustEmbedUnimplementedDataTransformServiceServer() {}
func (UnimplementedDataTransformServiceServer) testEmbeddedByValue()                              {}

// UnsafeDataTransformServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataTransformServiceServer will
// result in compilation errors.
type UnsafeDataTransformServiceServer interface {
	mustEmbedUnimplementedDataTransformServiceServer()
}

func RegisterDataTransformServiceServer(s grpc.ServiceRegistrar, srv DataTransformServiceServer) {
	// If the following call panics, it indicates UnimplementedDataTransformServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataTransformService_ServiceDesc, srv)
}

func _DataTransformService_TransformPatient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransformPatientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataTransformServiceServer).TransformPatient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataTransformService_TransformPatient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataTransformServiceServer).TransformPatient(ctx, req.(*TransformPatientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataTransformService_TransformClinicalSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransformClinicalSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataTransformServiceServer).TransformClinicalSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataTransformService_TransformClinicalSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataTransformServiceServer).TransformClinicalSummary(ctx, req.(*TransformClinicalSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataTransformService_TransformClinicalHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransformClinicalHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataTransformServiceServer).TransformClinicalHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataTransformService_TransformClinicalHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataTransformServiceServer).TransformClinicalHistory(ctx, req.(*TransformClinicalHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataTransformService_TransformPatientList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransformPatientListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataTransformServiceServer).TransformPatientList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataTransformService_TransformPatientList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataTransformServiceServer).TransformPatientList(ctx, req.(*TransformPatientListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataTransformService_TransformCohortExams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransformCohortExamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataTransformServiceServer).TransformCohortExams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataTransformService_TransformCohortExams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataTransformServiceServer).TransformCohortExams(ctx, req.(*TransformCohortExamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataTransformService_TransformCohortStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransformCohortStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataTransformServiceServer).TransformCohortStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataTransformService_TransformCohortStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataTransformServiceServer).TransformCohortStatistics(ctx, req.(*TransformCohortStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataTransformService_TransformProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransformProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataTransformServiceServer).TransformProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataTransformService_TransformProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataTransformServiceServer).TransformProjects(ctx, req.(*TransformProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataTransformService_ServiceDesc is the grpc.ServiceDesc for DataTransformService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataTransformService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "datatransform.v1.DataTransformService",
	HandlerType: (*DataTransformServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TransformPatient",
			Handler:    _DataTransformService_TransformPatient_Handler,
		},
		{
			MethodName: "TransformClinicalSummary",
			Handler:    _DataTransformService_TransformClinicalSummary_Handler,
		},
		{
			MethodName: "TransformClinicalHistory",
			Handler:    _DataTransformService_TransformClinicalHistory_Handler,
		},
		{
			MethodName: "TransformPatientList",
			Handler:    _DataTransformService_TransformPatientList_Handler,
		},
		{
			MethodName: "TransformCohortExams",
			Handler:    _DataTransformService_TransformCohortExams_Handler,
		},
		{
			MethodName: "TransformCohortStatistics",
			Handler:    _DataTransformService_TransformCohortStatistics_Handler,
		},
		{
			MethodName: "TransformProjects",
			Handler:    _DataTransformService_TransformProjects_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "datatransform/v1/datatransform.proto",
}
